spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/neetmitotsu/SpringCloudConfig
          search-paths: respo
      label: master