spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NeetMitotsu/Spring-cloud-config/tree/master/config-server
          search-paths: respo
      label: master
server:
  port: 8770